export const categories = [
    {id:1,courses:5,instructors: 12, students:251, name:'Data Science',img:'https://cdn-icons-png.flaticon.com/512/3716/3716795.png',course:[{id:1,Name:'Course Name',time:1,enrolled:100,price:'free',description:'This is a so long description of this course. Its an excellent course for skill development',requirement:'Anyone who can operate a computer and has internet connectivity will be able to join this course', level:'beginner', instructor:'Samiul Alim', image:'https://www.classcentral.com/report/wp-content/uploads/2020/06/top-100-course-pandemic.png'},
    {id:1,Name:'Course Name 2',time:2,enrolled:120,price:'free',description:'This is a so long description of this course. Its an excellent course for skill development',requirement:'Anyone who can operate a computer and has internet connectivity will be able to join this course', level:'beginner', instructor:'Samiul Alim', image:'https://www.classcentral.com/report/wp-content/uploads/2020/06/top-100-course-pandemic.png'}
] },
    {id:2,courses:3,instructors: 11, students:122, name:'AWS Certification',img:'https://cdn-icons-png.flaticon.com/512/149/149209.png',course:[{id:1,Name:'Course Name',time:1,enrolled:100,price:'free',description:'This is a so long description of this course. Its an excellent course for skill development',requirement:'Anyone who can operate a computer and has internet connectivity will be able to join this course', level:'beginner', instructor:'Samiul Alim', image:'https://www.classcentral.com/report/wp-content/uploads/2020/06/top-100-course-pandemic.png'}] },
    {id:3,courses:8,instructors: 16, students:214, name:'Web Development', img:'https://cdn-icons-png.flaticon.com/512/84/84471.png',course:[{id:1,Name:'Course Name',time:1,enrolled:100,price:'free',description:'This is a so long description of this course. Its an excellent course for skill development',requirement:'Anyone who can operate a computer and has internet connectivity will be able to join this course', level:'beginner', instructor:'Samiul Alim', image:'https://www.classcentral.com/report/wp-content/uploads/2020/06/top-100-course-pandemic.png'}] },
    {id:4,courses:4,instructors: 11, students:111, name:'Python',img:'https://cdn-icons-png.flaticon.com/512/5968/5968286.png',course:[{id:1,Name:'Course Name',time:1,enrolled:100,price:'free',description:'This is a so long description of this course. Its an excellent course for skill development',requirement:'Anyone who can operate a computer and has internet connectivity will be able to join this course', level:'beginner', instructor:'Samiul Alim', image:'https://www.classcentral.com/report/wp-content/uploads/2020/06/top-100-course-pandemic.png'}] },
    {id:5,courses:2,instructors: 17, students:432, name:'Excel', img: 'https://cdn-icons-png.flaticon.com/512/2822/2822607.png',course:[{id:1,Name:'Course Name',time:1,enrolled:100,price:'free',description:'This is a so long description of this course. Its an excellent course for skill development',requirement:'Anyone who can operate a computer and has internet connectivity will be able to join this course', level:'beginner', instructor:'Samiulgbfhgfhf Alim', image:'https://www.classcentral.com/report/wp-content/uploads/2020/06/top-100-course-pandemic.png'}] },
    {id:6,courses:6,instructors: 19, students:112, name:'NFT', img:'https://cdn-icons-png.flaticon.com/512/6699/6699362.png',course:[{id:1,Name:'Course Name',time:1,enrolled:100,price:'free',description:'This is a so long description of this course. Its an excellent course for skill development',requirement:'Anyone who can operate a computer and has internet connectivity will be able to join this course', level:'beginner', instructor:'Samiul Alim', image:'https://www.classcentral.com/report/wp-content/uploads/2020/06/top-100-course-pandemic.png'}] },
]